### ISSUE TITLE
start_kernel.py: error: unrecognized arguments: -f

### ISSUE THREAD

**Issue by pradipmoon** [shiralkarprashant/FCBF#5]
This is Pradip. I am trying to used your FCBF algorithm code to my datasets but getting an error. I have executed fcbf.py file 
![1](https://user-images.githubusercontent.com/45105923/54038796-4c843a00-41b9-11e9-9834-40d27ff0593a.png)

Also, I have tried through command line and getting an error as below;

![2](https://user-images.githubusercontent.com/45105923/54038804-54dc7500-41b9-11e9-962a-51dcb53026ff.png)

Can you please help me out, what I am doing wrong with the code?? I am executing the same code but it is not working.

**Comment by shiralkarprashant** [comment]
Are you by any chance using Python 3? This code is designed for Python 2.7. The README is now updated to reflect this. In Python 3, the string might already be decoded and hence the error. If so, try removing the ".decode('string_escape')" and see if it works. In Python 2.7, it works for me. See the following screen capture.

![image](https://user-images.githubusercontent.com/15031456/54075112-180f8d00-4250-11e9-9825-1631c0d5e559.png)

**Comment by pradipmoon** [comment]
Hi Prashant,

Thanks for your email.

Yes, I am using python 3.5 and I tried to remove .decode9('string_escape') but it is not working. Also, I am downgrade the python from 3.5 to 2.7 and trying to used your code. When  inpath = '../data/bot_online_dataset.dat' then getting message The file you specified does not exist.

When inpath = 'C:/Users/rahul.moon/.spyder/FCBF/data/lungcancer.csv' then getting below error

Reading file. Please wait ...
Input file loading failed. Please check the file.
('Error:', IndexError('tuple index out of range',))
Traceback (most recent call last):

  File "<ipython-input-25-eda370d79c5a>", line 273, in <module>
    main()

  File "<ipython-input-25-eda370d79c5a>", line 268, in main
    fcbf_wrapper(os.path.abspath(inpath), thresh, delim, header, classAt)

  File "<ipython-input-25-eda370d79c5a>", line 229, in fcbf_wrapper
    raise e

IndexError: tuple index out of range

I am not sure what I am doing wrong. Can you please look into it??

Thanks once again for your help and support.

Regards,
Pradip Moon


________________________________

**Comment by shiralkarprashant** [comment]
Without looking at your input file, it is hard to say. Does your input file have a header? If so, pass the header flag as another parameter in your command line call. Otherwise, this looks like a problem with the input data format.

**Comment by pradipmoon** [comment]
Pradip Moon has shared a OneDrive file with you. To view it, click the link below.


<https://1drv.ms/u/s!AvQh9aDS2ZWlhljKkxovGS9CdNGE>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AvQh9aDS2ZWlhljKkxovGS9CdNGE>

FLUXGENDER - Sample.csv<https://1drv.ms/u/s!AvQh9aDS2ZWlhljKkxovGS9CdNGE>



Hi Prashant,

Currently, I am testing your code on lungcancer.csv file which is in github. I have attached the file to this email. But its not working.

My file is FLUXGENDER.csv attached to this email and its have header.

Please check the same.

Regards,
Pradip Moon
________________________________

**Comment by shiralkarprashant** [comment]
Do you mean you tried with lungcancer.csv and it did not work? And you also tried with your file and did not work? Could you please share your exact command line calls?

**Comment by pradipmoon** [comment]
Hi Prashant,

I tried your lungcancer.csv file but its getting error

________________________________

**Comment by pradipmoon** [comment]
I have tried your lungcancer.csv file but its getting error as below;

Reading file. Please wait ...
Input file loading failed. Please check the file.
Error: tuple index out of range
Traceback (most recent call last):

  File "<ipython-input-2-d3d5d073f039>", line 273, in <module>
    main()

  File "<ipython-input-2-d3d5d073f039>", line 268, in main
    fcbf_wrapper(os.path.abspath(inpath), thresh, delim, header, classAt)

  File "<ipython-input-2-d3d5d073f039>", line 229, in fcbf_wrapper
    raise e

IndexError: tuple index out of range

Command line calls are as below;
[cid:5289a022-a142-4046-9074-f38fc0e6e45e]

________________________________

**Comment by pdatascientist** [comment]
Command line calls are as below;
![command](https://user-images.githubusercontent.com/46113054/54088544-f947ee00-4356-11e9-9a3c-e617655f6623.png)

**Comment by pdatascientist** [comment]
sorry its luncancer.csv file I have tried that but its not working.
getting same message The file you specified does not exist.

**Comment by shiralkarprashant** [comment]
Ok, this looks like it is not finding the file. I suggest you make sure that the file path is correct and take baby steps in debugging the issue. I cannot help you with this, since it is not related to FCBF code.  It works fine for both files for me. See the (truncated) output below.  

8c8590431a7c:FCBF$ python src/fcbf.py -inpath='./data/lungcancer.csv' -thresh=0.3
Reading file. Please wait ...
Success! Dimensions: 32 x 57
Performing FCBF selection. Please wait ...
X: (32, 56), y: 32
Done!

#Features selected: 2
Selected feature indices:
[[ 0.32054501 39.        ]
 [ 0.32017586 19.        ]]

File saved successfully. Path: ~/Projects/FCBF/data/features_lungcancer.csv


8c8590431a7c:FCBF$ python src/fcbf.py -inpath='~/Downloads/FLUXGENDER - Sample.csv' -thresh 0.5 -header True
Reading file. Please wait ...
Success! Dimensions: 499 x 4231
Performing FCBF selection. Please wait ...
X: (499, 4230), y: 499
Done!

#Features selected: 126
Selected feature indices:
[[1.00000000e+00 0.00000000e+00]
 [9.99552621e-01 3.01700000e+03]
 [9.99552621e-01 2.44000000e+02]
 [9.99552621e-01 1.20100000e+03]
 [9.99552621e-01 3.00000000e+02]
 [9.99552621e-01 1.12000000e+02]
 [9.99552621e-01 3.12200000e+03]
 ...
 [6.84344180e-01 3.32400000e+03]]

File saved successfully. Path: ~/Downloads/features_FLUXGENDER - Sample.csv

**Comment by pdatascientist** [comment]
Okay. Thanks Prashant for your help. Last questions

![Path](https://user-images.githubusercontent.com/46113054/54088684-7cb60f00-4358-11e9-8b93-e504889341ed.png)

Do I need to change this path for file?? For example lungcancer.csv

**Comment by shiralkarprashant** [comment]
No, this is just for testing purposes, when you don't provide any input parameters. By the way, it looks like you are using a Windows machine, so could you try replacing forward slashes in your file path to two backward slashes and see if that works?

Change `C:/Users/rahul.moon/.spyder/FCBF/data/lungcancer.csv` to `C:\\Users\\rahul.moon\\.spyder\\FCBF\\data\\lungcancer.csv`

**Comment by pdatascientist** [comment]
Tried replacing two backward slashes but getting same message file is not exist.

**Comment by shiralkarprashant** [comment]
Hm. Not sure then. I don't have a Windows machine to try on. Could you try accessing any other file in Python without using FCBF code? You could then use the same file path convention for the inpath parameter. I am closing this issue for now since it is unrelated, but if you face issues with the FCBF code, feel free to reopen or create a new issue. Thanks!

**Comment by pdatascientist** [comment]
Thanks Prashant for your help.

That means, this code is working only in Mac machine. Also, I have tried to change the inpath='../data/lungcancer.csv' in fcbf.py file and getting error
Reading file. Please wait ...
Input file loading failed. Please check the file.
Error: tuple index out of range
Traceback (most recent call last):

  File "<ipython-input-5-b13a55836784>", line 273, in <module>
    main()

  File "<ipython-input-5-b13a55836784>", line 268, in main
    fcbf_wrapper(os.path.abspath(inpath), thresh, delim, header, classAt)

  File "<ipython-input-5-b13a55836784>", line 229, in fcbf_wrapper
    raise e

IndexError: tuple index out of range

So, why I am getting error when file is in the location and it is appropriate format. I am using your file only.

**Comment by shiralkarprashant** [comment]
As I suggested before, can you try loading the same file in Python using your OWN code and using the SAME path? Does it work?
